name: shetkari_mitra
description: Shetkari Mitra - WebView for Mahabhumi (7/12 & 8A)
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.5.0
  provider: ^6.0.5
  permission_handler: ^10.4.0
  path_provider: ^2.0.15
  share_plus: ^6.4.0
  intl: ^0.18.0
  url_launcher: ^6.2.10
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/signshriram.jpg
    - assets/docs/security_audit_certificate.pdf
